version: '3.8'

services:
  db:
    build:
      context: ./db
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: okulovskiy
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ./app
    container_name: python_app
    depends_on:
      - db
volumes:
  db_data: